sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_products
        description: product of Greenweez / we have on row per product id with purchase price
        columns:
          - name: products_id
            tests:
               - unique
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product id found in each orders_id
        columns:
          - name : date_date
            description: purchase_date
        freshness:
          warn_after: {count: 90, period: day}
          error_after: {count: 120, period: day}
        tests:
            - unique:
                column_name: "(orders_id||'_'||pdt_id)"
      - name: ship
        identifier: raw_gz_ship
        description: shipping of Greenweez / we have shipping information in each orders_id
        columns:
          - name: orders_id
            tests:
               - unique